# Generated by Django 3.0.3 on 2020-03-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='album',
            field=models.ManyToManyField(through='account.FavoriteAlbum', to='music.Album'),
        ),
        migrations.AddField(
            model_name='user',
            name='artist',
            field=models.ManyToManyField(through='account.FavoriteArtist', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='discount_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.DiscountInformation'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.ManyToManyField(through='account.UserNotification', to='account.Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.ManyToManyField(through='account.FavoriteTrack', to='music.Track'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.DiscountPlan'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Playlist'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='account.PlaylistTrack', to='music.Track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Track'),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='favoritealbum',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.AddField(
            model_name='favoritealbum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
