# Generated by Django 3.0.3 on 2020-03-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'social_accounts',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_email',
        ),
        migrations.AddField(
            model_name='user',
            name='social_email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Gender'),
        ),
    ]
