# Generated by Django 3.0.3 on 2020-03-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200317_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
