# Generated by Django 3.0.3 on 2020-03-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(max_length=2000, null=True)),
                ('released_date', models.DateTimeField(null=True)),
                ('is_live', models.CharField(max_length=50, null=True)),
                ('is_single', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(max_length=2000, null=True)),
                ('facebook', models.URLField(max_length=2000, null=True)),
                ('twitter', models.URLField(max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='RelatedTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'related_tracks',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=50)),
                ('explicit', models.CharField(max_length=50, null=True)),
                ('master', models.CharField(max_length=50, null=True)),
                ('credit', models.TextField(null=True)),
                ('related_track', models.ManyToManyField(through='music.RelatedTrack', to='music.Track')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.AddField(
            model_name='relatedtrack',
            name='from_tracks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_tracks', to='music.Track'),
        ),
        migrations.AddField(
            model_name='relatedtrack',
            name='to_tracks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_tracks', to='music.Track'),
        ),
        migrations.CreateModel(
            name='RelatedArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_artists', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_artists', to='music.Artist')),
                ('to_artists', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_artists', to='music.Artist')),
            ],
            options={
                'db_table': 'related_artists',
                'unique_together': {('from_artists', 'to_artists')},
            },
        ),
        migrations.CreateModel(
            name='RelatedAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_albums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_albums', to='music.Album')),
                ('to_albums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_albums', to='music.Album')),
            ],
            options={
                'db_table': 'related_albums',
                'unique_together': {('from_albums', 'to_albums')},
            },
        ),
        migrations.CreateModel(
            name='ArtistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Track')),
            ],
            options={
                'db_table': 'artist_tracks',
            },
        ),
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
            options={
                'db_table': 'artist_albums',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.ManyToManyField(through='music.ArtistAlbum', to='music.Album'),
        ),
        migrations.AddField(
            model_name='artist',
            name='related_artist',
            field=models.ManyToManyField(through='music.RelatedArtist', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='track',
            field=models.ManyToManyField(through='music.ArtistTrack', to='music.Track'),
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Track')),
            ],
            options={
                'db_table': 'album_tracks',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='related_albums',
            field=models.ManyToManyField(through='music.RelatedAlbum', to='music.Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ManyToManyField(through='music.AlbumTrack', to='music.Track'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedtrack',
            unique_together={('from_tracks', 'to_tracks')},
        ),
    ]
