# Generated by Django 3.0.3 on 2020-03-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(max_length=2000, null=True)),
                ('released_date', models.DateTimeField(null=True)),
                ('is_live', models.BooleanField(null=True)),
                ('is_single', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('icon_url', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'social_media',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('music_url', models.URLField(max_length=2000, null=True)),
                ('time', models.TimeField()),
                ('is_explicit', models.BooleanField(null=True)),
                ('is_master', models.BooleanField(null=True)),
                ('credit', models.TextField(null=True)),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='ArtistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Track')),
            ],
            options={
                'db_table': 'artist_tracks',
            },
        ),
        migrations.CreateModel(
            name='ArtistSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(max_length=2000, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('social_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.SocialMedia')),
            ],
            options={
                'db_table': 'artist_social_media',
            },
        ),
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
            options={
                'db_table': 'artist_albums',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.ManyToManyField(through='music.ArtistAlbum', to='music.Album'),
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Gender'),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_media',
            field=models.ManyToManyField(through='music.ArtistSocialMedia', to='music.SocialMedia'),
        ),
        migrations.AddField(
            model_name='artist',
            name='track',
            field=models.ManyToManyField(through='music.ArtistTrack', to='music.Track'),
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Track')),
            ],
            options={
                'db_table': 'album_tracks',
            },
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
            options={
                'db_table': 'album_genres',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(through='music.AlbumGenre', to='music.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ManyToManyField(through='music.AlbumTrack', to='music.Track'),
        ),
    ]
