# Generated by Django 3.0.3 on 2020-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='explicit',
        ),
        migrations.RemoveField(
            model_name='track',
            name='master',
        ),
        migrations.AddField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_master',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_live',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_single',
            field=models.BooleanField(null=True),
        ),
    ]
