# Generated by Django 3.0.3 on 2020-03-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200311_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_url', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'social_media',
            },
        ),
        migrations.AlterUniqueTogether(
            name='relatedartist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relatedartist',
            name='from_artists',
        ),
        migrations.RemoveField(
            model_name='relatedartist',
            name='to_artists',
        ),
        migrations.AlterUniqueTogether(
            name='relatedtrack',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relatedtrack',
            name='from_tracks',
        ),
        migrations.RemoveField(
            model_name='relatedtrack',
            name='to_tracks',
        ),
        migrations.RemoveField(
            model_name='album',
            name='related_albums',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='related_artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='track',
            name='related_track',
        ),
        migrations.AddField(
            model_name='artist',
            name='music_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='time',
            field=models.DurationField(),
        ),
        migrations.DeleteModel(
            name='RelatedAlbum',
        ),
        migrations.DeleteModel(
            name='RelatedArtist',
        ),
        migrations.DeleteModel(
            name='RelatedTrack',
        ),
        migrations.AddField(
            model_name='artist',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.SocialMedia'),
        ),
    ]
