# Generated by Django 3.0.3 on 2020-03-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200312_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
