# Generated by Django 3.0.3 on 2020-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200312_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='time',
            field=models.TimeField(),
        ),
    ]
