# Generated by Django 3.0.3 on 2020-03-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200312_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='music_url',
        ),
        migrations.AddField(
            model_name='track',
            name='music_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
