# Generated by Django 3.0.3 on 2020-03-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200312_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='account_url',
            new_name='icon_url',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='user',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ArtistSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(max_length=2000, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('social_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.SocialMedia')),
            ],
            options={
                'db_table': 'artist_social_media',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='social_media',
            field=models.ManyToManyField(through='music.ArtistSocialMedia', to='music.SocialMedia'),
        ),
    ]
