# Generated by Django 3.0.3 on 2020-03-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200312_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
            options={
                'db_table': 'album_genres',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(through='music.AlbumGenre', to='music.Genre'),
        ),
    ]
