# Generated by Django 3.0.3 on 2020-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_artist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
